// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyProject.EFCore;

#nullable disable

namespace StudyProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250924100136_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyProject.EFCore.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("T_Persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            Gender = "Female",
                            Name = "yangmi"
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            Gender = "Female",
                            Name = "jingtian"
                        },
                        new
                        {
                            Id = 3,
                            Age = 500,
                            Gender = "Male",
                            Name = "wukong"
                        },
                        new
                        {
                            Id = 4,
                            Age = 1000,
                            Gender = "Male",
                            Name = "bajie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
